### PR TITLE
Fix Issue #124 - Revive with full HP/MP

### PR DESCRIPTION
**Pull request by crkellen**
This is a fix for #124.
The issue was Host players were getting their HP and MP set to MAX / 2. This was changed to be just MAX.
Additionally, Clients did not receive any MP at all. Whatever they had when they died, was what they kept. To fix this, a new line was added to set it to MAX as well.

### CODE REVIEW

**Comment by SheridanR** [comment]
Can't remember how mp was meant to be behave but the player reviving at half hp isn't an accident.

**Comment by crkellen** [comment]
What is the reason for Players starting at half HP? Having that as a feature only seems to add to the multiplayer snowballing issue.

**Comment by lheckemann** [comment]
I'm not here to guess at everyone's original intentions, but I think the snowballing effect is desirable: death is something to avoid very carefully, and certainly shouldn't be a routine occurrence from a gameplay perspective IMHO. It's already pretty unbalanced in that it allows surviving without enough food by simply taking it in turns to die, and increasing HP on revive just exacerbates that.

**Comment by addictgamer** [comment]
HP and MP should both be half the max when a player revives.
If client's don't receive any MP, that's a bug that should be fixed to match the host's/singleplayer behavior.

**Comment by crkellen** [comment]
I am still a bit confused as to why that is the intended behavior, but regardless, I can solve the issue tomorrow, as it is simply a single missing line in the clientsided code.
null

**Comment by addictgamer** [comment]
Thanks.

I'm going to close this pull request then.

**Pull request closed without merging**
