### PR TITLE
Query SDL for resolutions

### PR DESCRIPTION
**Pull request by lheckemann**
Based on @pwhelan's #60, but fixes the multiple-entry and 0x0 bugs.

### CODE REVIEW

**Comment by lheckemann** [comment]
Um... I think you broke it @addictgamer  :p

**Comment by addictgamer** [comment]
Ya, meant to push only one commit. Instead it pushed the whole branch. My bad.

**Comment by lheckemann** [comment]
```
git checkout resolution-auto
git fetch
git reset --hard @{u}
git cherry-pick 3b45538 
git push
```

Should fix it with only the one commit I presume you intended

**Comment by addictgamer** [comment]
Much better :)

**Comment by addictgamer** [comment]
Finished testing in Mac and Windows, looks like it works.
I dislike how it's throwing away all of the resolutions I use on my desktop, but this can be improved later.

Perhaps the stock resolutions we've been shipping with so far should arbitrarily get sorted into the list.

**Pull request merged**
