### PR TITLE
[MASTER] Fix Issue #120 - Cure Ailment does not remove Fire on Clients

### PR DESCRIPTION
**Pull request by crkellen**
See #132.

### CODE REVIEW

**Comment by crkellen** [comment]
I do believe I fixed cure ailment potion as well. That fix may be hiding somewhere. I will add it to this PR likely later today.
null

**Comment by crkellen** [comment]
Apologies that this took so long. I had forgotten about it for a little bit there. All fixed!

**Comment by addictgamer** [comment]
Potion of Cure Ailment works now, however:

> On use of 'cure ailment' spell, the flame particles are still present on the server player model and client player.

Potion of Cure Ailment stops the burning and makes the flame particles disappear on both the client's end and the server's end.
Spell of Cure Ailment stops the burning but only makes the flame particles disappear on the server's end.

**Comment by WALLOFJUSTICE** [comment]
Confirming that the spell of cure ailment cast by the client will only remove flames on the host.

If spell is cast by host, all players will have the flame effect removed from their views. Just need to get this 1 test case to solve.

**Comment by crkellen** [comment]
I may have incorrectly copy-pasted. I'll review today.
null

**Comment by crkellen** [comment]
The flames will Continue to be present as they will be fixed in the other pull request.
null

**Comment by addictgamer** [comment]
Ah. Is that in an existing PR or will you be making a new one?

**Comment by crkellen** [comment]
Already existing. If not then I never created it. I have a branch for it  sure. Heading home now, so I can handle this.
null

**Comment by addictgamer** [comment]
Right. I just tested this branch again based off of the latest master. The issue still occurs though for the cure ailment spell.

The cure ailments potion does makes the flames go away, the spell doesn't seem to be doing such.

@WALLOFJUSTICE can you confirm if the issue still occurs for you or if it's fixed?

**Comment by crkellen** [comment]
I can check on this tomorrow.
null

**Comment by crkellen** [comment]
OKay, I can totally confirm that I simply messed up somewhere down the line and did this:
Current:
```
if ( players[i]->entity->flags[BURNING] )
{
    players[i]->entity->flags[BURNING] = false;
    serverUpdateEntityFlag(players[clientnum]->entity, BURNING);
}
```

When it should be:
```
if ( players[i]->entity->flags[BURNING] )
{
    players[i]->entity->flags[BURNING] = false;
    serverUpdateEntityFlag(players[i]->entity, BURNING);
}
```

I believe I redid the PR or messed up somewhere, because I do remember testing it and having it work just fine, but clearly I somehow left it out of the actual PR. I'm going to test it real quick just to be 100% then i'll push the updated commit.

**Comment by addictgamer** [comment]
Confirm fixed.

**Pull request merged**
