### PR TITLE
Chest types 0 to 7 to be set by new additional editor sprites.

### PR DESCRIPTION
**Pull request by WALLOFJUSTICE**
Added settable chest types through using editor sprites 75-82, so players can make maps with fixed reward categories and not use random chests. Random chests in map generation and the original editor icon still behave the same.

Sprites.txt (I don't think this file is in the repo?) needs to be modified to include 8 new lines for these icons, I just added 8 chests icons to the end:
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png

New to this Git thing, hopefully all changes are there.

### CODE REVIEW

**Comment by addictgamer** [comment]
Awesome, will give it a run this weekend.

**Comment by addictgamer** [comment]
Oh, you based this off of the v2.0.4 branch? Master has been changed quite a bit, there will likely be merge conflicts.
Of particular note is the code has been updated to reflect several style guidelines, of biggest impact here are braces start on the following line rather than trailing on the current line.

**Comment by WALLOFJUSTICE** [comment]
Yeah I've just been working off a forked 2.0.4 from a month ago for my own modding changes, wasn't sure what was best in terms of actually getting it into the game

Is it easier for me to redo the changes in the latest master and repull request? There's not many but if it helps the GitHub workflow then I don't mind

**Comment by addictgamer** [comment]
That probably would be the easiest, especially if you're not accustomed to git and merges.

**Pull request closed without merging**
