### PR TITLE
Linkage issue fix, especially isMeleeWeapon is inlined

### PR DESCRIPTION
**Pull request by devnexen**
monster_goatman cant's access its symbol.
isRangedWeapon thus not necessary is more a "preventive" fix.

### CODE REVIEW

**Comment by devnexen** [comment]
It is a change to take with a grain of salt maybe those inlined function is just a first step of a more significant following change thus I might miss the big picture but ... just in case ;-)

**Comment by addictgamer** [comment]
I don't understand, what was the linkage issue?

**Comment by devnexen** [comment]
It does not compile for me, when it comes to monster_goatman.cpp.o object (which contains a call to isMeleeWeapon).

**Comment by devnexen** [comment]
screenshot_2017-08-26_05-54-40

In case I was messing up with my own barony-next branch I just cloned a fresh one from this repo and got same linkage error as you can see but again if it s a part of a bigger planned change not comitted yet but then I can drop this PR no problems.

**Comment by addictgamer** [comment]
Will have to look into this more, but I believe one of the other (more recent?) PRs addresses this already.

**Comment by devnexen** [comment]
Yes I think @crkellen chose to put the implementation in the headers approach instead. Whatever is best ;-)

**Comment by crkellen** [comment]
I'll review this after work today. I don't remember making a PR for any changes to inlining.
null

**Comment by devnexen** [comment]
Sorry I confused you with @lheckemann :-) this is the PR in question https://github.com/TurningWheel/Barony/pull/179

**Comment by lheckemann** [comment]
I prefer this one over mine (didn't see it when I was making mine!). Inline functions are confusing.

**Pull request merged**
