### PR TITLE
Fix Issue #242 - Chests should close before being broken

### PR DESCRIPTION
**Pull request by crkellen**
This is a fix for #242.
The issue is there was no call to `this->closeChest()` anywhere within the death code. Adding one solves the issues for both Client and Server.

However, for the one in the chest's inventory, they receive the message "You slam the chest shut". An alternate message could be implemented fairly easily.

### CODE REVIEW

**Comment by addictgamer** [comment]
Fixes the issue, but the player still receives the message `you slam the chest shut!`

**Comment by crkellen** [comment]
Sorry. I didn't add a new message, I had considered it, but at the time neglected to ask you what the message should say.
null

**Comment by crkellen** [comment]
Was going to handle last Sunday, but was unable to load the build without assets. Will handle Friday.
null

**Comment by crkellen** [comment]
This should be good to go now. I simply used entry `671 The chest is smashed into pieces!#`.

**Pull request merged**
