### PR TITLE
Fix Issue #102 - Host "On Fire" status does not disappear

### PR DESCRIPTION
**Pull request by crkellen**
This is a fix for #102.
The issue is caused by if statement checks that say if the player is a Client, update your status. These statements were removed from both stepping in water, and drinking from a fountain.

Cases that need to be verified:
- ~~Player using Cure Ailment Spell~~ - Verified that it works on Clients viewing the host. Cannot fully verify due to #120 
- ~~Player using Cure Ailment Potion~~ - Verified that it works on Clients viewing the host. Cannot fully verify due to #120
- ~~Player's "On Fire" Status timing out~~ - Verified that Clients will continue to see the effects on the Host after it times out. **Commit https://github.com/TurningWheel/Barony/pull/119/commits/3340353d96b45155e86a2fb7ada6306846183987**

Just a thought, I will look into this tomorrow, but perhaps the function:
~~'serverUpdateEntityFlag()' is the cause of the issues, not the check.~~
The issue is that the Server handles removing the "On Fire" status on Clients, but not setting Clients to be on fire.. There is a
`if ( multiplayer != CLIENT )` check before every time `flags[BURNING] = false` then the check after which never executes:
`if ( PLAYER_NUM > 0 )` which would call the 'serverUpdateEntityFlag()'. Removing the check fixes this, although in general, the net code structure needs a redesign at some point, as it is ambiguous how well it aligns with proper Server Authoritative structure.

### CODE REVIEW

**Comment by addictgamer** [comment]
What's the status of this? Is the fix completed and ready to be merged?

**Comment by crkellen** [comment]
Yes this is completed. I can verify as such in 9 hours or so.
null

**Comment by addictgamer** [comment]
Ok, just wasn't sure on the status of it.

**Comment by crkellen** [comment]
After reviewing the post I can see why. I'll edit it as well when I can.
null

**Comment by addictgamer** [comment]
Merged in #203

**Comment by addictgamer** [comment]
Resolved in #203

**Pull request closed without merging**
