### PR TITLE
[MASTER] Fix Issue #126 - Client is not affected by Slow Spell

### PR DESCRIPTION
**Pull request by crkellen**
See #134.

### CODE REVIEW

**Comment by addictgamer** [comment]
> Works. No notification that slow effect has stopped, but I've seen this addressed in another PR

Where has this been resolved?

**Comment by addictgamer** [comment]
> Where has this been resolved?

I see it. Good.

**Comment by addictgamer** [comment]
@crkellen Out of curiosity, were there any issues with the cold spell?

**Comment by WALLOFJUSTICE** [comment]
Cold had same issue, fix was in this PR

**Comment by crkellen** [comment]
Correct, exact same code was implemented in cold spell, the fix is part of this PR.
null

**Pull request merged**
