### PR TITLE
OpenAL build fix

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
I left out the editor part which has nothing to do with sound but I was guessing someone already into it.

**Review by WALLOFJUSTICE — APPROVED** [review]

**Comment by addictgamer** [comment]
Were these all the changes required? I'm still getting an error about OPENAL_SOUND and stuff like that in player.hpp...
```
player.hpp:750:3: error: ‘OPENAL_SOUND’ does not name a type
player.hpp:751:3: error: ‘ALboolean’ does not name a type; did you mean ‘GLboolean’?
```

**Comment by addictgamer** [comment]
@devnexen d93c832 fixed those issues for me, can you verify everything's still good for you before I merge this in?

**Comment by devnexen** [comment]
All good

**Pull request merged**
