### PR TITLE
Data dir next

### PR DESCRIPTION
**Pull request by lheckemann**
#64 ported to barony-next

### CODE REVIEW

**Comment by addictgamer** [comment]
So, it seems there's an issue with books. When I tried to pick up the journal in the starting level, the game crashed in items.cpp line 367:
```snprintf(&tempstr[c], 1024 - c, language[1007], books[appearance % numbooks]->name);```

Inspecting the game state, I found out numbooks is 0.
Looking at log.txt, I found:
```
[02-56-58] compiling books...
[02-56-58] Warning: discoveredbooks->first and last do not exist. No books in /books/ directory?
```
My datad-r was ./ and the books directory definitely was populated.

**Comment by lheckemann** [comment]
Yep, I've been trying to work that one out. I'll get back to you once I've fixed it.

**Comment by lheckemann** [comment]
Turns out `==` has higher precedence than `&` >_>

Fixed.

**Comment by addictgamer** [comment]
Yep, that fixed it.

I did notice if datadir isn't passed in with a trailing slash, it fails to load the random player names files.

**Pull request merged**
